apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: employee-management
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: employeedb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
